[package]
name = "cluster_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
csv = "1.3.0"
flate2 = "1.0.33"
serde = { version = "1.0.210", features = ["derive"] }
ureq = "2.10.1"
